const express = require("express");
const cors = require("cors");
const app = express();
const PORT = 5000;

app.use(cors());
app.use(express.json());

// Simple keyword to emoji dictionary
const emojiMap = {
  happy: "😃",
  sad: "😢",
  love: "❤️",
  angry: "😡",
  nervous: "😰",
  food: "🍔",
  sleep: "😴",
  party: "🎉",
  work: "💻",
  hello: "👋",
  bye: "👋",
  hi: "👋",
  hey: "👋",
  welcome: "🙏",
  goodbye: "👋",
  goodmorning: "🌅",
  goodafternoon: "☀️",
  goodevening: "🌇",
   
  joy: "😂",
  excited: "🤩",
  love: "❤️",
  like: "👍",
  tired: "😴",
  scared: "😱",
  surprised: "😮",
  confused: "😕",
  calm: "😌",
  disappointed: "😞",

  pizza: "🍕",
  burger: "🍔",
  icecream: "🍨",
  coffee: "☕",
  tea: "🍵",
  water: "💧",
  sleep: "😴",
  work: "💻",
  computer: "💻",
  laptop: "💻",
  phone: "📱",
  party: "🎉",
  music: "🎵",
  book: "📖",
  study: "📚",
  travel: "✈️",
  car: "🚗",
  bike: "🚲",

  cat: "🐱",
  dog: "🐶",
  lion: "🦁",
  tiger: "🐯",
  bear: "🐻",
  panda: "🐼",
  koala: "🐨",
  monkey: "🐵",
  rabbit: "🐰",
  fox: "🦊",
  wolf: "🐺",
  deer: "🦌",
  elephant: "🐘",
  horse: "🐴",
  cow: "🐮",
  pig: "🐷",
  mouse: "🐭",
  rat: "🐀",
  giraffe: "🦒",
  rhinoceros: "🦏",
  hippopotamus: "🦛",
  kangaroo: "🦘",
  camel: "🐫",
  buffalo: "🐃",

  // Birds
  bird: "🐦",
  penguin: "🐧",
  owl: "🦉",
  dove: "🕊️",
  eagle: "🦅",
  duck: "🦆",
  swan: "🦢",
  flamingo: "🦩",
  peacock: "🦚",
  parrot: "🦜",
  chicken: "🐔",
  rooster: "🐓",

  // Reptiles & amphibians
  snake: "🐍",
  turtle: "🐢",
  lizard: "🦎",
  crocodile: "🐊",
  frog: "🐸",
  salamander: "🦎",

  // Sea animals
  fish: "🐟",
  tropicalfish: "🐠",
  blowfish: "🐡",
  dolphin: "🐬",
  whale: "🐳",
  whale2: "🐋",
  shark: "🦈",
  octopus: "🐙",
  squid: "🦑",
  crab: "🦀",
  lobster: "🦞",
  shrimp: "🦐",
  crab2: "🦀",
  clam: "🦪",

  // Insects
  bug: "🐛",
  ant: "🐜",
  bee: "🐝",
  butterfly: "🦋",
  snail: "🐌",
  spider: "🕷️",
  scorpion: "🦂",
  mosquito: "🦟",
  fly: "🪰",

  // Nature — plants & flowers
  tree: "🌳",
  palm: "🌴",
  cactus: "🌵",
  herb: "🌿",
  shamrock: "☘️",
  fourleafclover: "🍀",
  mapleleaf: "🍁",
  fallenleaf: "🍂",
  leaf: "🍃",
  seedling: "🌱",
  blossom: "🌼",
  flower: "🌸",
  tulip: "🌷",
  rose: "🌹",
  sunflower: "🌻",
  hibiscus: "🌺",
  bouquet: "💐",
  mushroom: "🍄",
  pine: "🌲",
  evergreen: "🌲",
  volcano: "🌋",
  mountain: "⛰️",
  snowcappedmountain: "🏔️",
  desert: "🏜️",
  beach: "🏖️",
  island: "🏝️",
  forest: "🌲",
  moon: "🌙",
  sun: "☀️",
  stars: "⭐",
  sparkles: "✨",
  rainbow: "🌈",

  // Sports
  soccer: "⚽",
  football: "🏈",
  basketball: "🏀",
  volleyball: "🏐",
  baseball: "⚾",
  tennis: "🎾",
  badminton: "🏸",
  pingpong: "🏓",
  golf: "⛳",
  icehockey: "🏒",
  fieldhockey: "🏑",
  cricket: "🏏",
  skiing: "🎿",
  snowboard: "🏂",
  boxing: "🥊",
  martialarts: "🥋",
  wrestling: "🤼",
  surfing: "🏄",
  swimming: "🏊",
  running: "🏃",
  cycling: "🚴",
  weightlifting: "🏋️",
  rockclimbing: "🧗",
  skateboarding: "🛹",
  bowling: "🎳",
  fishing: "🎣",
  gymnastics: "🤸",
  
  // Activities / Hobbies
  music: "🎵",
  guitar: "🎸",
  piano: "🎹",
  violin: "🎻",
  drum: "🥁",
  art: "🎨",
  painting: "🖌️",
  photography: "📷",
  movie: "🎬",
  theater: "🎭",
  reading: "📖",
  writing: "✍️",
  travel: "✈️",
  camping: "🏕️",
  hiking: "🥾",
  dancing: "💃",
  singing: "🎤",
  cooking: "👩‍🍳",
  shopping: "🛍️",
  video_game: "🎮",
  board_game: "🎲",
  
  // Objects — Electronics & Tools
  phone: "📱",
  laptop: "💻",
  desktop: "🖥️",
  tablet: "📲",
  camera: "📷",
  television: "📺",
  radio: "📻",
  printer: "🖨️",
  lightbulb: "💡",
  clock: "⏰",
  watch: "⌚",
  key: "🔑",
  lock: "🔒",
  unlocked: "🔓",
  hammer: "🔨",
  wrench: "🔧",
  screwdriver: "🪛",
  tools: "🛠️",
  magnet: "🧲",
  scissors: "✂️",
  paperclip: "📎",
  pushpin: "📌",
  envelope: "✉️",
  mailbox: "📫",
  package: "📦",
  shopping_bag: "🛍️",
  money: "💰",
  credit_card: "💳",
  gem: "💎",
  trophy: "🏆",
  medal: "🏅",

  apple: "🍎",
  green_apple: "🍏",
  pear: "🍐",
  peach: "🍑",
  cherry: "🍒",
  strawberry: "🍓",
  watermelon: "🍉",
  lemon: "🍋",
  banana: "🍌",
  pineapple: "🍍",
  mango: "🥭",
  grapes: "🍇",
  kiwi: "🥝",
  coconut: "🥥",

  // Food — vegetables
  tomato: "🍅",
  carrot: "🥕",
  corn: "🌽",
  potato: "🥔",
  sweet_potato: "🍠",
  broccoli: "🥦",
  mushroom: "🍄",
  cucumber: "🥒",
  leafy_green: "🥬",
  pepper: "🫑",
  onion: "🧅",
  garlic: "🧄",
  
  // Food — meals/snacks
  bread: "🍞",
  croissant: "🥐",
  baguette: "🥖",
  cheese: "🧀",
  egg: "🥚",
  pancake: "🥞",
  bacon: "🥓",
  hamburger: "🍔",
  fries: "🍟",
  pizza: "🍕",
  hotdog: "🌭",
  sandwich: "🥪",
  taco: "🌮",
  burrito: "🌯",
  sushi: "🍣",
  ramen: "🍜",
  soup: "🥣",
  bento: "🍱",
  donut: "🍩",
  cake: "🍰",
  birthday_cake: "🎂",
  pie: "🥧",
  chocolate: "🍫",
  candy: "🍬",
  lollipop: "🍭",
  ice_cream: "🍨",
  shaved_ice: "🍧",
  popsicle: "🧊",
  
  // Drinks
  water: "💧",
  coffee: "☕",
  tea: "🍵",
  milk: "🥛",
  juice: "🧃",
  wine: "🍷",
  beer: "🍺",
  cocktail: "🍸",
  tropical_drink: "🍹",
  sake: "🍶",
  champagne: "🍾",
  cup: "🥤",
  
  // Travel / Places
  airplane: "✈️",
  helicopter: "🚁",
  rocket: "🚀",
  train: "🚆",
  metro: "🚇",
  tram: "🚊",
  bus: "🚌",
  trolleybus: "🚎",
  taxi: "🚕",
  car: "🚗",
  suv: "🚙",
  truck: "🚚",
  bike: "🚲",
  scooter: "🛵",
  motorbike: "🏍️",
  ship: "🛳️",
  ferry: "⛴️",
  sailboat: "⛵",
  motorboat: "🛥️",
  anchor: "⚓",
  beach: "🏖️",
  mountain: "⛰️",
  desert: "🏜️",
  city: "🏙️",
  house: "🏠",
  hotel: "🏨",
  castle: "🏰",
  tent: "⛺",
  bridge: "🌉",

  heart: "❤️",
  black_heart: "🖤",
  orange_heart: "🧡",
  yellow_heart: "💛",
  green_heart: "💚",
  blue_heart: "💙",
  purple_heart: "💜",
  white_heart: "🤍",
  broken_heart: "💔",
  star: "⭐",
  glowing_star: "🌟",
  sparkle: "✨",
  fire: "🔥",
  warning: "⚠️",
  check_mark: "✔️",
  cross_mark: "❌",
  question_mark: "❓",
  exclamation_mark: "❗",
  plus: "➕",
  minus: "➖",
  multiply: "✖️",
  divide: "➗",
  infinity: "♾️",
  copyright: "©️",
  registered: "®️",
  trade_mark: "™️",
  
  // Symbols — arrows
  arrow_up: "⬆️",
  arrow_down: "⬇️",
  arrow_left: "⬅️",
  arrow_right: "➡️",
  arrow_upper_right: "↗️",
  arrow_upper_left: "↖️",
  arrow_lower_right: "↘️",
  arrow_lower_left: "↙️",
  back_arrow: "🔙",
  end_arrow: "🔚",
  return_arrow: "↩️",
  repeat: "🔁",
  shuffle: "🔀",
  
  // Symbols — zodiac / weather / miscellaneous
  sun: "☀️",
  moon: "🌙",
  cloud: "☁️",
  rain: "🌧️",
  snowflake: "❄️",
  lightning: "⚡",
  umbrella: "☂️",
  comet: "☄️",
  rainbow: "🌈",
  crescent_moon: "🌙",
  shooting_star: "🌠",
  
  // Flags — countries (few examples, can expand to all)
  flag_us: "🇺🇸",
  flag_uk: "🇬🇧",
  flag_india: "🇮🇳",
  flag_canada: "🇨🇦",
  flag_australia: "🇦🇺",
  flag_germany: "🇩🇪",
  flag_france: "🇫🇷",
  flag_japan: "🇯🇵",
  flag_china: "🇨🇳",
  flag_russia: "🇷🇺",
  flag_brazil: "🇧🇷",
  flag_italy: "🇮🇹",
  flag_mexico: "🇲🇽",
  flag_south_korea: "🇰🇷",
  flag_saudi_arabia: "🇸🇦",
  flag_singapore: "🇸🇬",
  flag_spain: "🇪🇸",
  
  // Special characters / misc
  skull: "💀",
  ghost: "👻",
  alien: "👽",
  robot: "🤖",
  clown: "🤡",
  jack_o_lantern: "🎃",
  bell: "🔔",
  musical_note: "🎵",
  peace: "☮️",
  yin_yang: "☯️",
  recycle: "♻️",
  atom: "⚛️",
  wheelchair: "♿",
  biohazard: "☣️",
  radioactive: "☢️",
  thermometer: "🌡️",
  telescope: "🔭",
  microscope: "🔬",

  // Clothing
  t_shirt: "👕",
  shirt: "👔",
  jeans: "👖",
  dress: "👗",
  kimono: "👘",
  bikini: "👙",
  swimsuit: "🩱",
  shorts: "🩳",
  socks: "🧦",
  shoes: "👟",
  high_heel: "👠",
  boot: "👢",
  crown: "👑",
  hat: "🎩",
  helmet: "⛑️",
  scarf: "🧣",
  gloves: "🧤",
  coat: "🧥",
  
  // Accessories
  glasses: "👓",
  sunglasses: "🕶️",
  purse: "👛",
  handbag: "👜",
  backpack: "🎒",
  wallet: "👝",
  watch: "⌚",
  ring: "💍",
  necklace: "📿",
  umbrella: "☂️",
  key: "🔑",
  
  // Extended objects
  book: "📖",
  notebook: "📓",
  pencil: "✏️",
  pen: "🖊️",
  fountain_pen: "🖋️",
  paintbrush: "🖌️",
  palette: "🎨",
  scissors: "✂️",
  ruler: "📏",
  compass: "🧭",
  telescope: "🔭",
  microscope: "🔬",
  magnet: "🧲",
  bell: "🔔",
  lamp: "💡",
  candle: "🕯️",
  lantern: "🏮",
  
  // More Flags (regional / world)
  flag_afghanistan: "🇦🇫",
  flag_albania: "🇦🇱",
  flag_algeria: "🇩🇿",
  flag_argentina: "🇦🇷",
  flag_armenia: "🇦🇲",
  flag_austria: "🇦🇹",
  flag_azerbaijan: "🇦🇿",
  flag_bangladesh: "🇧🇩",
  flag_belgium: "🇧🇪",
  flag_bolivia: "🇧🇴",
  flag_bulgaria: "🇧🇬",
  flag_chile: "🇨🇱",
  flag_colombia: "🇨🇴",
  flag_croatia: "🇭🇷",
  flag_czech_republic: "🇨🇿",
  flag_denmark: "🇩🇰",
  flag_egypt: "🇪🇬",
  flag_finland: "🇫🇮",
  flag_greece: "🇬🇷",
  flag_hungary: "🇭🇺",
  flag_iceland: "🇮🇸",
  flag_indonesia: "🇮🇩",
  flag_ireland: "🇮🇪",
  flag_israel: "🇮🇱",
  flag_italy: "🇮🇹",
  flag_jamaica: "🇯🇲",
  flag_japan: "🇯🇵",
  flag_kenya: "🇰🇪",
  flag_luxembourg: "🇱🇺",
  flag_malaysia: "🇲🇾",
  flag_morocco: "🇲🇦",
  flag_netherlands: "🇳🇱",
  flag_new_zealand: "🇳🇿",
  flag_nigeria: "🇳🇬",
  flag_norway: "🇳🇴",
  flag_philippines: "🇵🇭",
  flag_poland: "🇵🇱",
  flag_portugal: "🇵🇹",
  flag_qatar: "🇶🇦",
  flag_romania: "🇷🇴",
  flag_singapore: "🇸🇬",
  flag_south_africa: "🇿🇦",
  flag_south_korea: "🇰🇷",
  flag_sweden: "🇸🇪",
  flag_switzerland: "🇨🇭",
  flag_thailand: "🇹🇭",
  flag_turkey: "🇹🇷",
  flag_uk: "🇬🇧",
  flag_ukraine: "🇺🇦",
  flag_united_arab_emirates: "🇦🇪",
  flag_usa: "🇺🇸",
  flag_vietnam: "🇻🇳",
  flag_zimbabwe: "🇿🇼",

   // Extended Food & Drinks
  bread: "🍞",
  croissant: "🥐",
  baguette: "🥖",
  cheese: "🧀",
  egg: "🥚",
  bacon: "🥓",
  pancake: "🥞",
  waffle: "🧇",
  meat: "🥩",
  steak: "🥩",
  drumstick: "🍗",
  seafood: "🦞",
  shrimp: "🦐",
  oyster: "🦪",
  sushi: "🍣",
  bento: "🍱",
  curry: "🍛",
  rice_ball: "🍙",
  rice: "🍚",
  spaghetti: "🍝",
  ramen: "🍜",
  hot_dog: "🌭",
  burger: "🍔",
  fries: "🍟",
  donut: "🍩",
  cookie: "🍪",
  chocolate: "🍫",
  candy: "🍬",
  lollipop: "🍭",
  cake: "🍰",
  pie: "🥧",
  ice_cream: "🍨",
  shaved_ice: "🍧",
  milk: "🥛",
  coffee: "☕",
  tea: "🍵",
  sake: "🍶",
  wine: "🍷",
  cocktail: "🍸",
  beer: "🍺",
  tropical_drink: "🍹",
  champagne: "🥂",

  // Extended Nature & Animals
  cactus: "🌵",
  evergreen_tree: "🌲",
  deciduous_tree: "🌳",
  palm_tree: "🌴",
  mushroom: "🍄",
  tulip: "🌷",
  rose: "🌹",
  sunflower: "🌻",
  blossom: "🌼",
  herb: "🌿",
  four_leaf_clover: "🍀",
  maple_leaf: "🍁",
  fallen_leaf: "🍂",
  leaf_fluttering: "🍃",
  seedling: "🌱",
  dog: "🐶",
  cat: "🐱",
  mouse: "🐭",
  hamster: "🐹",
  rabbit: "🐰",
  fox: "🦊",
  bear: "🐻",
  panda: "🐼",
  koala: "🐨",
  tiger: "🐯",
  lion: "🦁",
  cow: "🐮",
  pig: "🐷",
  frog: "🐸",
  octopus: "🐙",
  crab: "🦀",
  lobster: "🦞",
  snail: "🐌",
  butterfly: "🦋",
  bee: "🐝",
  ant: "🐜",
  lady_beetle: "🐞",
  spider: "🕷️",
  scorpion: "🦂",
  tropical_fish: "🐠",
  blowfish: "🐡",
  dolphin: "🐬",
  whale: "🐳",
  shark: "🦈",
  crocodile: "🐊",
  snake: "🐍",
  dragon_face: "🐲",
  dragon: "🐉",
  whale_face: "🐋",
  unicorn: "🦄",

  // Miscellaneous Rare / Fun
  magic_wand: "🪄",
  crystal_ball: "🔮",
  puppet: "🪆",
  piñata: "🪅",
  kite: "🪁",
  yo_yo: "🪀",
  boomerang: "🪃",
  nesting_dolls: "🪆",
  sloth: "🦥",
  otter: "🦦",
  skunk: "🦨",
  flamingo: "🦩",
  beaver: "🦫",
  orangutan: "🦧",
  mule: "🫎",
  feather: "🪶",
  drum: "🥁",
  violin: "🎻",
  saxophone: "🎷",
  trumpet: "🎺",
  accordion: "🪗",
  long_drum: "🪘",
  maracas: "🪇",
  banjo: "🪕",
  skateboard: "🛹",
  surfboard: "🏄",
  sled: "🛷",
  parachute: "🪂",

  // Hand Gestures
  thumbs_up: "👍",
  thumbs_down: "👎",
  ok_hand: "👌",
  victory_hand: "✌️",
  crossed_fingers: "🤞",
  love_you_gesture: "🤟",
  call_me_hand: "🤙",
  raising_hand: "🙋",
  folded_hands: "🙏",
  waving_hand: "👋",
  clap: "👏",
  muscle: "💪",
  pinching_hand: "🤏",

  // Faces/Expressions
  face_with_rolling_eyes: "🙄",
  zany_face: "🤪",
  woozy_face: "🥴",
  pleading_face: "🥺",
  lying_face: "🤥",
  shushing_face: "🤫",
  face_with_symbols_on_mouth: "🤬",
  face_with_monocle: "🧐",
  nerd_face: "🤓",
  cowboy_hat_face: "🤠",

  // Arrows & Shapes
  arrow_up: "⬆️",
  arrow_down: "⬇️",
  arrow_left: "⬅️",
  arrow_right: "➡️",
  arrow_upper_right: "↗️",
  arrow_upper_left: "↖️",
  arrow_lower_right: "↘️",
  arrow_lower_left: "↙️",
  double_arrow_up: "⏫",
  double_arrow_down: "⏬",
  recycle: "♻️",
  infinity: "♾️",
  warning: "⚠️",
  no_entry: "🚫",
  biohazard: "☣️",
  radioactive: "☢️",

  // Math Symbols
  plus: "+",
  minus: "-",
  multiplication: "×",
  division: "÷",
  equal: "=",
  not_equal: "≠",
  approximately_equal: "≈",
  infinity_symbol: "∞",
  pi: "π",
  percent: "%",
  degree: "°",
  micro: "µ",
  integral: "∫",
  summation: "∑",
  square_root: "√",
  delta: "Δ",

  // Misc Symbols
  star: "⭐",
  glowing_star: "🌟",
  sparkles: "✨",
  comet: "☄️",
  fire: "🔥",
  droplet: "💧",
  wave: "🌊",
  snowflake: "❄️",
  snowman: "☃️",
  umbrella: "☂️",
  moon: "🌙",
  sun: "☀️",
  earth: "🌍",
  globe_with_meridians: "🌐",
  cloud: "☁️",
  rainbow: "🌈",
  cyclone: "🌀",
  fog: "🌫️",

  car: "🚗",
  taxi: "🚕",
  bus: "🚌",
  tram: "🚊",
  train: "🚆",
  metro: "🚇",
  monorail: "🚝",
  bullet_train: "🚄",
  airplane: "✈️",
  helicopter: "🚁",
  rocket: "🚀",
  satellite: "🛰️",
  ship: "🚢",
  ferry: "⛴️",
  sailboat: "⛵",
  bicycle: "🚲",
  motorcycle: "🏍️",
  scooter: "🛴",

  // Technology
  phone: "📱",
  computer: "💻",
  desktop: "🖥️",
  keyboard: "⌨️",
  printer: "🖨️",
  mouse: "🖱️",
  joystick: "🕹️",
  camera: "📷",
  video_camera: "📹",
  television: "📺",
  radio: "📻",
  phone_receiver: "📞",
  pager: "📟",
  fax: "📠",

  // Office & Stationery
  book: "📖",
  notebook: "📓",
  closed_book: "📕",
  ledger: "📒",
  scroll: "📜",
  pen: "🖊️",
  pencil: "✏️",
  fountain_pen: "🖋️",
  paintbrush: "🖌️",
  crayon: "🖍️",
  scissors: "✂️",
  ruler: "📏",
  compass: "🧭",

  // Flags
  flag_us: "🇺🇸",
  flag_india: "🇮🇳",
  flag_uk: "🇬🇧",
  flag_canada: "🇨🇦",
  flag_australia: "🇦🇺",
  flag_germany: "🇩🇪",
  flag_france: "🇫🇷",
  flag_japan: "🇯🇵",
  flag_china: "🇨🇳",
  flag_brazil: "🇧🇷",
  flag_russia: "🇷🇺",
  flag_south_korea: "🇰🇷",
  flag_italy: "🇮🇹",
  flag_mexico: "🇲🇽",
  flag_spain: "🇪🇸",
  flag_south_africa: "🇿🇦",

  // Rare Objects
  telescope: "🔭",
  microscope: "🔬",
  magnet: "🧲",
  alembic: "⚗️",
  test_tube: "🧪",
  petri_dish: "🧫",
  syringe: "💉",
  pill: "💊",
  door: "🚪",
  bed: "🛏️",
  couch: "🛋️",
  bathtub: "🛁",
  shower: "🚿",
  toilet: "🚽",
  key: "🔑",
  lock: "🔒",
  unlocked: "🔓",
  bell: "🔔",
  alarm_clock: "⏰",
  hourglass: "⏳",
  watch: "⌚",
  
};

// API route
app.post("/translate", (req, res) => {
  const { text } = req.body;
  if (!text) return res.json({ emoji: "" });

  let words = text.toLowerCase().split(/\s+/);
  let result = "";

  words.forEach((word) => {
    if (emojiMap[word]) {
      result += emojiMap[word] + " ";
    } else {
      result += "❓ "; // fallback
    }
  });

  res.json({ emoji: result.trim() });
});

app.listen(PORT, () => {
  console.log(`✅ Backend running on http://localhost:${PORT}`);
});
